default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5 
  username: postgres
  password: Waithira2013

development:
  <<: *default
  database: hello_rails_back_end_development

test:
  <<: *default
  database: hello_rails_back_end_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: hello_rails_back_end_production
  username: hello_rails_back_end
  password: <%= ENV["HELLO_RAILS_BACK_END_DATABASE_PASSWORD"] %>
